# Generated by Django 6.1.1 on 2026-09-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='current_stage',
            field=models.CharField(choices=[('research', 'Research Agent'), ('planning', 'Planning Agent'), ('writing', 'Writing Agent'), ('completed', 'Completed'), ('failed', 'Failed')], default='research', max_length=20),
        ),
    ]
