# Generated by Django 6.1.1 on 2026-09-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_research_current_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='in_progress', max_length=20),
        ),
    ]
